### PR TITLE
Migrated table definitions to the ingest system version 7

### PR DESCRIPTION
**Pull request by iagaponenko**

### CODE REVIEW

**Comment by fjammes** [comment]
Thanks @iagaponenko , however it seems the format is not yet correct. Indeed, I cannot load the "dpdd_ref" table. See line around "2021-11-03T08:30:59.8578298Z 2021-11-03 08:30:50,230 - qserv.jsonparser - CRITICAL - invalid parameters of the request, ex: HttpRequestBody::required<T>[static] required parameter latitude_key is missing in the request body" in the log file: https://pipelines.actions.githubusercontent.com/hVgirA0GbhE6G2nSbGtRLheThMu4fWpVS49cy1Lk1nHtYrWTlG/_apis/pipelines/1/runs/2388/signedlogcontent/18?urlExpires=2021-11-03T08%3A41%3A08.7989011Z&urlSigningMethod=HMACV1&urlSignature=ylWKwYA%2FhVjR%2BjizZuVbmxlDcPvREAw2Rcf2U7NVym0%3D.

According to the documentation https://confluence.lsstcorp.org/display/DM/Ingest%3A+11.1.2.5.+Register+a+new+table, I do not understand which values (or empty value) I have to provide for "latitude_key" and "longitude_key" for partitioned, non-director tables. Could you please help me?

**Comment by iagaponenko** [comment]
@fjammes I have double-checked all configurations that I modified in these folders:
```
tests/data/cosmoDC2/
tests/data/DC2/
tests/data/DC2-errors/
```
All looks correct to me.
I have also tested all of them in the `large6` cluster at NCSA that has API version 7 deployed. Everything worked just fine. The documentation on version 7 says that parameters `latitude_key` and `longitude_key` are required for the `director` tables. The `dependent` tables may or may not have these keys. You may see more on this here as well: https://confluence.lsstcorp.org/display/DM/Ingest%3A+9.6.+Ingesting+catalogs+with+many+director+tables

I suspect you have. a problem in the configuration of your test. Perhaps you are not testing against Verison 7. Please, check what you see when you're calling this service:
```
/meta/version
```

**Comment by fjammes** [comment]
@iagaponenko maybe this link to the log is working: https://github.com/lsst-dm/qserv-ingest/runs/4090074244?check_suite_focus=true ?

**Comment by iagaponenko** [comment]
@fjammes I have inspected the log file, and it looks like the problem is caused by not using the modified config files of this PR. I'm still seeing these. For example, for table `position` I'm seeing the attribute `is_director` that must not be in there:
```
2021-11-03 08:40:13,397 - qserv.replicationclient - DEBUG - Starting a table registration request: http://qserv-repl-ctl-0.qserv-repl-ctl:8080/ingest/table/ with {'database': 'dc2_run2_1i_dr1b', 'table': 'position', 'auth_key': '', 'is_partitioned': 1, 'chunk_id_key': 'chunkId', 'sub_chunk_id_key': 'subChunkId', 'is_director': 1,
...
```
It looks like the CI is misconfigured by not using this PR. It seems to be using the `master` branch of this package.

**Comment by fjammes** [comment]
Thanks @iagaponenko it works fine now: https://github.com/lsst/qserv-operator/actions/runs/1418632400. Dependencies management between qserv-operator, qserv-ingest and test datasets is no so great and error prone, so it is difficult to move all these components concurrently. I have cherry-picked your commit in my branch, could this replace your PR approval?

**Comment by iagaponenko** [comment]
@fjammes thanks! I will merge my PR into the `master` branch of the package.

**Comment by fjammes** [comment]
Ok go forward, but please note that this may break the qserv-ingest master branch CI, which does not uses yet v7. This is not blocking but we may define a better in the long term.

**Pull request merged**
